<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="DESKTOP-U9BEVS1" name="com.openkart.Testclass.TC_ProductDisplay" tests="4" failures="1" timestamp="2021-09-02T21:01:37 IST" time="34.186" errors="0">
  <testcase name="VerifyRatingSucessMessage" time="34.186" classname="com.openkart.Testclass.TC_ProductDisplay">
    <failure type="java.lang.AssertionError" message="expected [ Thank you for your review. It has been submitted to the webmaster for approval.] but found [Your Name]">
      <![CDATA[java.lang.AssertionError: expected [ Thank you for your review. It has been submitted to the webmaster for approval.] but found [Your Name]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.openkart.Testclass.TC_ProductDisplay.VerifyRatingSucessMessage(TC_ProductDisplay.java:63)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VerifyRatingSucessMessage -->
  <system-out/>
  <testcase name="VerifyAvailabilityStatus" classname="com.openkart.Testclass.TC_ProductDisplay">
    <skipped/>
  </testcase> <!-- VerifyAvailabilityStatus -->
  <system-out/>
  <testcase name="VerifyTheBrandNameCodeProductName_001" classname="com.openkart.Testclass.TC_ProductDisplay">
    <skipped/>
  </testcase> <!-- VerifyTheBrandNameCodeProductName_001 -->
  <system-out/>
  <testcase name="VerifyTheDefaultQuantiyOne" classname="com.openkart.Testclass.TC_ProductDisplay">
    <skipped/>
  </testcase> <!-- VerifyTheDefaultQuantiyOne -->
  <system-out/>
</testsuite> <!-- com.openkart.Testclass.TC_ProductDisplay -->
